### ISSUE TITLE
docker dependency optional ?

### ISSUE THREAD

**Issue by olevole** [cristifalcas/puppet-prometheus#1]
I have installed https://forge.puppet.com/garethr/docker and when i try to install puppet-prometheus got:
~~~
Error: Could not install module 'cristifalcas-prometheus' (v1.6.0)
  Dependency 'cristifalcas-docker' (v5.5.0) would overwrite /etc/puppetlabs/modules/public/docker
    Currently, 'garethr-docker' (v5.3.0) is installed to that directory
    Use `puppet module install --ignore-dependencies` to install only this module
~~~

It may be better to do Docker feature optional ? I would like to use this module for installation and configuration prometheus without Docker

**Comment by cristifalcas** [comment]
I pushed a new module, where docker is no longer a dependency.
