### ISSUE TITLE
no parameter named 'purge_config_dir' 

### ISSUE THREAD

**Issue by olevole** [cristifalcas/puppet-prometheus#2]
version from github master causes an error:
~~~
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Prometheus]: has no parameter named 'purge_config_dir' at /etc/puppetlabs/code/environments/production/manifests/prod_nodes.pp:368:2 on node XXXX
~~~

Manifest ( taken from the examples page ):
~~~
class { '::prometheus':
    package_ensure        => 'latest',
    purge_config_dir      => true,
...
~~~

**Comment by cristifalcas** [comment]
Hello @olevole , thank you for opening this issue.

The parameter was removed some time ago, but I missed to update the Readme also. 

This was decided because the same folder is shared between prometheus and alertmanager.

**Comment by cristifalcas** [comment]
I have updated now the documentation
